# Load Datasets and device related CVES

In [2]:
import pandas as pd

# Load the dataset
cve_dataset = pd.read_excel('Datasets/cve_data.xlsx')
cwe_dataset = pd.read_excel('Datasets/cwe_data.xlsx')
# List of infusion-related CVEs
infusion_cves = cve_dataset[['CVE ID']]

# Extract device related vulenrabilities

In [3]:
# Filter dataset to match only the CVEs in the infusion list
infusion_vulnerabilities = cve_dataset

# Display the filtered dataset
infusion_vulnerabilities.shape

(10, 14)

In [5]:
infusion_vulnerabilities

,CVE ID,Description,Weaknesses,baseScore,baseSeverity,attackVector,attackComplexity,privilegesRequired,userInteraction,confidentialityImpact,integrityImpact,availabilityImpact,exploitabilityScore,CVSS Version
0,CVE-2014-5433,An unauthenticated remote attacker may be able...,CWE-255; CWE-312,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0
1,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",CWE-732,9.4,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,LOW,HIGH,3.9,3.1
2,CVE-2014-5434,Baxter SIGMA Spectrum Infusion System version ...,CWE-259; CWE-798,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0
3,CVE-2020-12047,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",CWE-259; CWE-798,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.1
4,CVE-2020-12043,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",CWE-672,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.1
5,CVE-2014-5431,Baxter SIGMA Spectrum Infusion System version ...,CWE-259; CWE-798,6.8,MEDIUM,PHYSICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,0.9,3.0
6,CVE-2020-12045,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",CWE-259; CWE-798,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.1
7,CVE-2020-12040,Sigma Spectrum Infusion System v's6.x (model 3...,CWE-319,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.1
8,CVE-2020-12039,Baxter Sigma Spectrum Infusion Pumps Sigma Spe...,CWE-259; CWE-798,2.4,LOW,PHYSICAL,LOW,NONE,NONE,LOW,NONE,NONE,0.9,3.1
9,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,CWE-287; CWE-592,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0

# CVE Device vulnerability Preprocessing for Merge

In [67]:
infusion_vulnerabilities['Weaknesses'] = infusion_vulnerabilities['Weaknesses'].astype(str).fillna('')
# Split the 'Weaknesses' column into a list
infusion_vulnerabilities['Weaknesses'] = infusion_vulnerabilities['Weaknesses'].str.split('; ')

# Explode the 'Weaknesses' column so each CWE ID has its own row
infusion_vulnerabilities = infusion_vulnerabilities.explode('Weaknesses', ignore_index=True)

infusion_vulnerabilities_data = infusion_vulnerabilities
# Remove prefix 
infusion_vulnerabilities_data['Weaknesses'] = infusion_vulnerabilities_data['Weaknesses'].astype(str)
infusion_vulnerabilities_data['Weaknesses'] = infusion_vulnerabilities_data['Weaknesses'].str.replace("CWE-", "", regex=True)

# CWE DATA Preprocessing for Merge

In [68]:
# Rename CWE dataset columns with 'cwe_' prefix (only if not already prefixed)
if not any(col.startswith('cwe_') for col in cwe_dataset.columns):
    cwe_dataset = cwe_dataset.add_prefix('cwe_')

# Rename 'cwe_CWE_ID' column to match 'Weaknesses' column
cwe_dataset.rename(columns={'cwe_CWE_ID': 'Weaknesses'}, inplace=True)

# Rename 'cwe_CWE_ID' column to match 'Weaknesses' column
cwe_dataset.rename(columns={'cwe_CWE_ID': 'Weaknesses'}, inplace=True)

# Ensure 'Weaknesses' column in CWE dataset is also of type string
cwe_dataset['Weaknesses'] = cwe_dataset['Weaknesses'].astype(str)

# Merge CVE Device Vulnerabilities and CWE weaknesses

In [69]:
# Merge CWE details into infusion vulnerabilities dataset
device_weaknesses = infusion_vulnerabilities_data.merge(cwe_dataset, on='Weaknesses', how='left')

# Rename 'Weaknesses' column back to 'CWE ID' for clarity
device_weaknesses.rename(columns={'Weaknesses': 'CWE ID'}, inplace=True)

# Display the merged dataset
device_weaknesses.head()

,CVE ID,Description,CWE ID,baseScore,baseSeverity,attackVector,attackComplexity,privilegesRequired,userInteraction,confidentialityImpact,integrityImpact,availabilityImpact,exploitabilityScore,CVSS Version,cwe_Unnamed: 0,cwe_Name,cwe_Abstraction,cwe_Structure,cwe_Status,cwe_Description,cwe_Extended_Description,cwe_Related_Weaknesses,cwe_Weakness_Ordinality,cwe_Language_Name,cwe_Technology_Class,cwe_Alternate_Terms,cwe_Alternate_Terms_With_Descriptions,cwe_Background_Details,cwe_Modes_Of_Introduction,cwe_Likelihood_Of_Exploit,cwe_Common_Consequences,cwe_Detection_Methods,cwe_Potential_Mitigations,cwe_Demonstrative_Examples,cwe_Observed_Examples,cwe_Related_Attack_Patterns,cwe_Mapping_Notes
0,CVE-2014-5433,An unauthenticated remote attacker may be able...,255,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CVE-2014-5433,An unauthenticated remote attacker may be able...,312,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,449.0,Cleartext Storage of Sensitive Information,Base,Simple,Draft,The product stores sensitive information in cl...,NaN,"CWE-311 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Mobile, Cloud Computing, ICS/OT",NaN,NaN,NaN,Architecture and Design: OMISSION: This weakne...,NaN,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A,Intro: The following code excerpt stores a pla...,Reference: CVE-2022-30275 | Description: Remot...,37,Usage: Allowed | Rationale: This CWE entry is ...
2,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",732,9.4,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,LOW,HIGH,3.9,3.1,835.0,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,"1, 122, 127, 17, 180, 206, 234, 60, 61, 62, 642",Usage: Allowed-with-Review | Rationale: While ...
3,CVE-2014-5434,Baxter SIGMA Spectrum Infusion System version ...,259,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,394.0,Use of Hard-coded Password,Variant,Simple,Draft,"The product contains a hard-coded password, wh...",NaN,"CWE-798 (ChildOf, View: 1000, Ordinal: Primary...",Primary,NaN,ICS/OT,NaN,NaN,NaN,Implementation: REALIZATION: This weakness is ...,High,Scope: Access Control | Impact: Gain Privilege...,Method: Manual Analysis | Effectiveness: N/A |...,Phase: Architecture and Design | Description: ...,Intro: The following code uses a hard-coded pa...,Reference: CVE-2022-29964 | Description: Distr...,NaN,Usage: Allowed | Rationale: This CWE entry is ...
4,CVE-2014-5434,Baxter SIGMA Spectrum Infusion System version ...,798,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,888.0,Use of Hard-coded Credentials,Base,Simple,Draft,"The product contains hard-coded credentials, s...",NaN,"CWE-1391 (ChildOf, View: 1000, Ordinal: Primar...",Primary,NaN,"Mobile, ICS/OT",NaN,NaN,NaN,Architecture and Design: REALIZATION: This wea...,High,Scope: Access Control | Impact: Bypass Protect...,Method: Black Box | Effectiveness: Moderate | ...,Phase: Architecture and Design | Description: ...,Intro: The following code uses a hard-coded pa...,Reference: CVE-2022-29953 | Description: Condi...,"191, 70",Usage: Allowed | Rationale: This CWE entry is ...

In [70]:
pd.set_option('display.max_columns', None)  # Show all columns

# Load CAPEC Data and Preprocess for Merge

In [71]:
# Load CAPEC dataset
capec_dataset = pd.read_excel('Datasets/capec_data.xlsx')

# Preprocess CAPEC Data for Merge

In [72]:
# Ensure CAPEC_ID is a string and strip whitespace
capec_dataset['CAPEC_ID'] = capec_dataset['CAPEC_ID'].astype(str).str.strip()

# Prefix CAPEC dataset columns with 'capec_' (only if not already prefixed)
capec_dataset.columns = [f'capec_{col}' if not col.startswith('capec_') else col for col in capec_dataset.columns]

# Rename CAPEC_ID column in capec_dataset to match CWE column for merging
capec_dataset.rename(columns={'capec_CAPEC_ID': 'cwe_Related_Attack_Patterns'}, inplace=True)

# Preprocess DeviceWeaknesses df for merge

In [73]:

# Ensure Related_Attack_Patterns in merged_df is string and clean it
device_weaknesses['cwe_Related_Attack_Patterns'] = device_weaknesses['cwe_Related_Attack_Patterns'].astype(str).str.strip()

# Split multiple CAPEC IDs into separate rows
device_weaknesses['cwe_Related_Attack_Patterns'] = device_weaknesses['cwe_Related_Attack_Patterns'].str.split(',')
device_weaknesses = device_weaknesses.explode('cwe_Related_Attack_Patterns')

# Clean whitespace again after explode
device_weaknesses['cwe_Related_Attack_Patterns'] = device_weaknesses['cwe_Related_Attack_Patterns'].str.strip()

# Merge Device weaknesses with Capec Attack Patterns

In [74]:
# Merge CAPEC details based on Related Attack Patterns
device_Attack_Pattern = device_weaknesses.merge(capec_dataset, on='cwe_Related_Attack_Patterns', how='left')

# Rename back to CAPEC_ID for clarity
device_Attack_Pattern.rename(columns={'cwe_Related_Attack_Patterns': 'CAPEC_ID'}, inplace=True)

# Debug: Check for missing CAPEC names
missing = device_Attack_Pattern[device_Attack_Pattern['capec_Name'].isnull()]
print("Missing CAPEC Names for these IDs:\n", missing['CAPEC_ID'].unique())
device_Attack_Pattern = device_Attack_Pattern.loc[:, ~device_Attack_Pattern.columns.str.contains('^Unnamed')]

# Show final DataFrame
device_Attack_Pattern.head()

Missing CAPEC Names for these IDs:
 ['nan']

,CVE ID,Description,CWE ID,baseScore,baseSeverity,attackVector,attackComplexity,privilegesRequired,userInteraction,confidentialityImpact,integrityImpact,availabilityImpact,exploitabilityScore,CVSS Version,cwe_Unnamed: 0,cwe_Name,cwe_Abstraction,cwe_Structure,cwe_Status,cwe_Description,cwe_Extended_Description,cwe_Related_Weaknesses,cwe_Weakness_Ordinality,cwe_Language_Name,cwe_Technology_Class,cwe_Alternate_Terms,cwe_Alternate_Terms_With_Descriptions,cwe_Background_Details,cwe_Modes_Of_Introduction,cwe_Likelihood_Of_Exploit,cwe_Common_Consequences,cwe_Detection_Methods,cwe_Potential_Mitigations,cwe_Demonstrative_Examples,cwe_Observed_Examples,CAPEC_ID,cwe_Mapping_Notes,capec_Unnamed: 0,capec_Name,capec_Abstraction,capec_Status,capec_Description,capec_Extended_Description,capec_Likelihood_Of_Attack,capec_Typical_Severity,capec_Related_Attack_Patterns,capec_Execution_Flow,capec_Prerequisites,capec_Skills_Required,capec_Resources_Required,capec_Consequences,capec_Mitigations,capec_Example_Instances,capec_Related_Weaknesses,capec_Taxonomy_Mappings,capec_Mitre_Techniques
0,CVE-2014-5433,An unauthenticated remote attacker may be able...,255,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CVE-2014-5433,An unauthenticated remote attacker may be able...,312,9.8,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,3.0,449.0,Cleartext Storage of Sensitive Information,Base,Simple,Draft,The product stores sensitive information in cl...,NaN,"CWE-311 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Mobile, Cloud Computing, ICS/OT",NaN,NaN,NaN,Architecture and Design: OMISSION: This weakne...,NaN,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A,Intro: The following code excerpt stores a pla...,Reference: CVE-2022-30275 | Description: Remot...,37,Usage: Allowed | Rationale: This CWE entry is ...,247.0,Retrieve Embedded Sensitive Data,Detailed,Draft,An attacker examines a target system to find s...,NaN,High,Very High,CAPEC-167 (ChildOf),Step 1: Explore - [Identify Target] Attacker i...,In order to feasibly execute this type of atta...,Medium: The attacker must possess knowledge of...,The attacker must possess access to the system...,Scope: Confidentiality | Impact: Read Data || ...,NaN,Using a tool such as 'strings' or similar to p...,"CWE-226, CWE-311, CWE-525, CWE-312, CWE-314, C...",ATTACK: 1005 - Data from Local System || ATTAC...,1005 - Data from Local System || 1552.004 - Un...
2,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",732,9.4,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,LOW,HIGH,3.9,3.1,835.0,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,1,Usage: Allowed-with-Review | Rationale: While ...,0.0,Accessing Functionality Not Properly Constrain...,Standard,Draft,"In applications, particularly web applications...",NaN,High,High,"CAPEC-122 (ChildOf), CAPEC-17 (CanPrecede)",Step 1: Explore - [Survey] The attacker survey...,The application must be navigable in a manner ...,Low: In order to discover unrestricted resourc...,None: No specialized resources are required to...,"Scope: Confidentiality, Access Control, Author...","In a J2EE setting, administrators can associat...",Implementing the Model-View-Controller (MVC) w...,"CWE-276, CWE-285, CWE-434, CWE-693, CWE-732, C...",ATTACK: 1574.010 - Hijack Execution Flow: Serv...,1574.010 - Hijack Execution Flow
3,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",732,9.4,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,LOW,HIGH,3.9,3.1,835.0,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,122,Usage: Allowed-with-Review | Rationale: While ...,24.0,Privilege Abuse,Meta,Draft,An adversary is able to exploit features of th...,If access control mechanisms are absent or mis...,High,Medium,CAPEC-664 (CanPrecede),NaN,The target must have misconfigured their acces...,Low: Adversary can leverage privileged feature...,None: No specialized resources are required to...,Scope: Integrity | Impact: Modify Data || Scop...,Configure account privileges such privileged/a...,Improperly configured account privileges allow...,"CWE-269, CWE-732, CWE-1317",ATTACK: 1548 - Abuse Elevation Control Mechanism,1548 - Abuse Elevation Control Mechanism
4,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",732,9.4,CRITICAL,NETWORK,LOW,NONE,NONE,HIGH,LOW,HIGH,3.9,3.1,835.0,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,127,Usage: Allowed-with-Review | Rationale: While ...,29.0,Directory Indexing,Detailed,Draft,An adversary crafts a request to a target that...,NaN,High,Medium,CAPEC-54 (ChildOf),Step 1: Explore - [Directory Discovery] Use a ...,The target must be misconfigured to return a l...,Low: To issue the request to URL without given...,Ability to send HTTP requests to a web applica...,Scope: Confidentiality | Impact: Read Data,1. Using blank index.html: putting blank index...,The adversary uses directory listing to view s...,"CWE-424, CWE-425, CWE-288, CWE-285, CWE-732, C...",ATTACK: 1083 - File and Directory Discovery,1083 - File and Directory Discovery

# Load Mitre ATT&CK DATASET

In [75]:
mitre_df = pd.read_excel('Datasets/techniques.xlsx')
mitre_df['supports remote'] = (
    mitre_df['supports remote']
    .fillna(0)      # replace NaN with 0
    .astype(int)    # now safe to convert
)

mitre_df['supports remote'] = mitre_df['supports remote'].astype('int')
# or if you prefer True/False:
mitre_df['supports remote'] = mitre_df['supports remote'].astype('bool')

mitre_df['impact type'] = mitre_df['impact type'].astype('category')

mitre_df = mitre_df.rename(columns={'description': 'tech_description'})



mitre_df.head()

,ID,STIX ID,name,tech_description,url,created,last modified,domain,version,tactics,detection,platforms,data sources,is sub-technique,sub-technique of,defenses bypassed,contributors,permissions required,supports remote,system requirements,impact type,effective permissions,relationship citations
0,T1548,attack-pattern--67720091-eee3-4d2d-ae16-826456...,Abuse Elevation Control Mechanism,Adversaries may circumvent mechanisms designed...,https://attack.mitre.org/techniques/T1548,30 January 2020,15 October 2024,enterprise-attack,1.4,"Defense Evasion, Privilege Escalation",Monitor the file system for files that have th...,"IaaS, Identity Provider, Linux, Office Suite, ...","Command: Command Execution, File: File Metadat...",False,NaN,NaN,NaN,"Administrator, User",False,NaN,NaN,NaN,"(Citation: TrendMicro RaspberryRobin 2022),(Ci..."
1,T1548.002,attack-pattern--120d5519-3098-4e1c-9191-2aa612...,Abuse Elevation Control Mechanism: Bypass User...,Adversaries may bypass UAC mechanisms to eleva...,https://attack.mitre.org/techniques/T1548/002,30 January 2020,21 April 2023,enterprise-attack,2.1,"Defense Evasion, Privilege Escalation",There are many ways to perform UAC bypasses wh...,Windows,"Command: Command Execution, Process: Process C...",True,T1548,Windows User Account Control,Casey Smith; Stefan Kanthak,"Administrator, User",False,NaN,NaN,Administrator,"(Citation: Microsoft BlackCat Jun 2022),(Citat..."
2,T1548.004,attack-pattern--b84903f0-c7d5-435d-a69e-de47cc...,Abuse Elevation Control Mechanism: Elevated Ex...,Adversaries may leverage the <code>Authorizati...,https://attack.mitre.org/techniques/T1548/004,30 January 2020,19 October 2022,enterprise-attack,1.0,"Defense Evasion, Privilege Escalation",Consider monitoring for <code>/usr/libexec/sec...,macOS,"Process: OS API Execution, Process: Process Cr...",True,T1548,NaN,"Erika Noerenberg, @gutterchurl, Carbon Black; ...","Administrator, User",False,NaN,NaN,root,"(Citation: Carbon Black Shlayer Feb 2019),"
3,T1548.001,attack-pattern--6831414d-bb70-42b7-8030-d4e06b...,Abuse Elevation Control Mechanism: Setuid and ...,An adversary may abuse configurations where an...,https://attack.mitre.org/techniques/T1548/001,30 January 2020,15 March 2023,enterprise-attack,1.1,"Defense Evasion, Privilege Escalation",Monitor the file system for files that have th...,"Linux, macOS","Command: Command Execution, File: File Metadat...",True,T1548,NaN,NaN,User,False,NaN,NaN,NaN,"(Citation: OSX Keydnap malware),(Citation: ANS..."
4,T1548.003,attack-pattern--1365fe3b-0f50-455d-b4da-266ce3...,Abuse Elevation Control Mechanism: Sudo and Su...,Adversaries may perform sudo caching and/or us...,https://attack.mitre.org/techniques/T1548/003,30 January 2020,14 March 2022,enterprise-attack,1.0,"Defense Evasion, Privilege Escalation","On Linux, auditd can alert every time a user's...","Linux, macOS","Command: Command Execution, File: File Modific...",True,T1548,NaN,NaN,User,False,NaN,NaN,root,"(Citation: hexed osx.dok analysis 2019),(Citat..."

# Preprocess and Merge Device_Attack_Patterns with Mitre Techniques And Tactics dataset

In [76]:


# Step 0: Split the column by '||' and explode it
device_Attack_Pattern['capec_Mitre_Techniques'] = device_Attack_Pattern['capec_Mitre_Techniques'].str.split(r'\s*\|\|\s*')
device_Attack_Pattern = device_Attack_Pattern.explode('capec_Mitre_Techniques')

# Step 1: Extract technique ID from exploded entries (everything before ' -')
device_Attack_Pattern['Technique_ID_Only'] = device_Attack_Pattern['capec_Mitre_Techniques'].str.extract(r'^([\d\.]+)')

# Step 2: Remove the 'T' prefix in mitre_df's ID column
mitre_df['Technique_ID_Only'] = mitre_df['ID'].str.replace('T', '', regex=False)

# # Step 3: Merge on the numeric technique ID
device_Attack_Pattern = device_Attack_Pattern.merge(
    mitre_df,
    how='left',
    on='Technique_ID_Only'
)

# Optional: Display first few rows
print(device_Attack_Pattern.head())

           CVE ID                                        Description CWE ID  \
0   CVE-2014-5433  An unauthenticated remote attacker may be able...    255
1   CVE-2014-5433  An unauthenticated remote attacker may be able...    312
2   CVE-2014-5433  An unauthenticated remote attacker may be able...    312
3  CVE-2020-12041  The Baxter Spectrum WBM (v17, v20D29, v20D30, ...    732
4  CVE-2020-12041  The Baxter Spectrum WBM (v17, v20D29, v20D30, ...    732

   baseScore baseSeverity attackVector attackComplexity privilegesRequired  \
0        9.8     CRITICAL      NETWORK              LOW               NONE
1        9.8     CRITICAL      NETWORK              LOW               NONE
2        9.8     CRITICAL      NETWORK              LOW               NONE
3        9.4     CRITICAL      NETWORK              LOW               NONE
4        9.4     CRITICAL      NETWORK              LOW               NONE

  userInteraction confidentialityImpact integrityImpact availabilityImpact  \
0            NONE                  HIGH            HIGH               HIGH
1            NONE                  HIGH            HIGH               HIGH
2            NONE                  HIGH            HIGH               HIGH
3            NONE                  HIGH             LOW               HIGH
4            NONE                  HIGH             LOW               HIGH

   exploitabilityScore  CVSS Version  cwe_Unnamed: 0  \
0                  3.9           3.0             NaN
1                  3.9           3.0           449.0
2                  3.9           3.0           449.0
3                  3.9           3.1           835.0
4                  3.9           3.1           835.0

                                            cwe_Name cwe_Abstraction  \
0                                                NaN             NaN
1         Cleartext Storage of Sensitive Information            Base
2         Cleartext Storage of Sensitive Information            Base
3  Incorrect Permission Assignment for Critical R...           Class
4  Incorrect Permission Assignment for Critical R...           Class

  cwe_Structure cwe_Status                                    cwe_Description  \
0           NaN        NaN                                                NaN
1        Simple      Draft  The product stores sensitive information in cl...
2        Simple      Draft  The product stores sensitive information in cl...
3        Simple      Draft  The product specifies permissions for a securi...
4        Simple      Draft  The product specifies permissions for a securi...

                            cwe_Extended_Description  \
0                                                NaN
1                                                NaN
2                                                NaN
3  When a resource is given a permission setting ...
4  When a resource is given a permission setting ...

                              cwe_Related_Weaknesses cwe_Weakness_Ordinality  \
0                                                NaN                     NaN
1  CWE-311 (ChildOf, View: 1000, Ordinal: Primary...                     NaN
2  CWE-311 (ChildOf, View: 1000, Ordinal: Primary...                     NaN
3  CWE-285 (ChildOf, View: 1000, Ordinal: Primary...                     NaN
4  CWE-285 (ChildOf, View: 1000, Ordinal: Primary...                     NaN

  cwe_Language_Name                      cwe_Technology_Class  \
0               NaN                                       NaN
1               NaN           Mobile, Cloud Computing, ICS/OT
2               NaN           Mobile, Cloud Computing, ICS/OT
3               NaN  Cloud Computing, Not Technology-Specific
4               NaN  Cloud Computing, Not Technology-Specific

  cwe_Alternate_Terms cwe_Alternate_Terms_With_Descriptions  \
0                 NaN                                   NaN
1                 NaN                                   NaN
2                 NaN                                   NaN
3                 NaN                                   NaN
4                 NaN                                   NaN

  cwe_Background_Details                          cwe_Modes_Of_Introduction  \
0                    NaN                                                NaN
1                    NaN  Architecture and Design: OMISSION: This weakne...
2                    NaN  Architecture and Design: OMISSION: This weakne...
3                    NaN  Architecture and Design: N/A | Implementation:...
4                    NaN  Architecture and Design: N/A | Implementation:...

  cwe_Likelihood_Of_Exploit  \
0                       NaN
1                       NaN
2                       NaN
3                      High
4                      High

                             cwe_Common_Consequences  \
0                                                NaN
1  Scope: Confidentiality | Impact: Read Applicat...
2  Scope: Confidentiality | Impact: Read Applicat...
3  Scope: Confidentiality | Impact: Read Applicat...
4  Scope: Confidentiality | Impact: Read Applicat...

                               cwe_Detection_Methods  \
0                                                NaN
1  Method: Automated Static Analysis | Effectiven...
2  Method: Automated Static Analysis | Effectiven...
3  Method: Automated Static Analysis | Effectiven...
4  Method: Automated Static Analysis | Effectiven...

                           cwe_Potential_Mitigations  \
0                                                NaN
1           Phase: Implementation | Description: N/A
2           Phase: Implementation | Description: N/A
3  Phase: Implementation | Description: N/A || Ph...
4  Phase: Implementation | Description: N/A || Ph...

                          cwe_Demonstrative_Examples  \
0                                                NaN
1  Intro: The following code excerpt stores a pla...
2  Intro: The following code excerpt stores a pla...
3  Intro: The following code sets the umask of th...
4  Intro: The following code sets the umask of th...

                               cwe_Observed_Examples CAPEC_ID  \
0                                                NaN      nan
1  Reference: CVE-2022-30275 | Description: Remot...       37
2  Reference: CVE-2022-30275 | Description: Remot...       37
3  Reference: CVE-2022-29527 | Description: Go ap...        1
4  Reference: CVE-2022-29527 | Description: Go ap...      122

                                   cwe_Mapping_Notes  capec_Unnamed: 0  \
0                                                NaN               NaN
1  Usage: Allowed | Rationale: This CWE entry is ...             247.0
2  Usage: Allowed | Rationale: This CWE entry is ...             247.0
3  Usage: Allowed-with-Review | Rationale: While ...               0.0
4  Usage: Allowed-with-Review | Rationale: While ...              24.0

                                          capec_Name capec_Abstraction  \
0                                                NaN               NaN
1                   Retrieve Embedded Sensitive Data          Detailed
2                   Retrieve Embedded Sensitive Data          Detailed
3  Accessing Functionality Not Properly Constrain...          Standard
4                                    Privilege Abuse              Meta

  capec_Status                                  capec_Description  \
0          NaN                                                NaN
1        Draft  An attacker examines a target system to find s...
2        Draft  An attacker examines a target system to find s...
3        Draft  In applications, particularly web applications...
4        Draft  An adversary is able to exploit features of th...

                          capec_Extended_Description  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  If access control mechanisms are absent or mis...

  capec_Likelihood_Of_Attack capec_Typical_Severity  \
0                        NaN                    NaN
1                       High              Very High
2                       High              Very High
3                       High                   High
4                       High                 Medium

                capec_Related_Attack_Patterns  \
0                                         NaN
1                         CAPEC-167 (ChildOf)
2                         CAPEC-167 (ChildOf)
3  CAPEC-122 (ChildOf), CAPEC-17 (CanPrecede)
4                      CAPEC-664 (CanPrecede)

                                capec_Execution_Flow  \
0                                                NaN
1  Step 1: Explore - [Identify Target] Attacker i...
2  Step 1: Explore - [Identify Target] Attacker i...
3  Step 1: Explore - [Survey] The attacker survey...
4                                                NaN

                                 capec_Prerequisites  \
0                                                NaN
1  In order to feasibly execute this type of atta...
2  In order to feasibly execute this type of atta...
3  The application must be navigable in a manner ...
4  The target must have misconfigured their acces...

                               capec_Skills_Required  \
0                                                NaN
1  Medium: The attacker must possess knowledge of...
2  Medium: The attacker must possess knowledge of...
3  Low: In order to discover unrestricted resourc...
4  Low: Adversary can leverage privileged feature...

                            capec_Resources_Required  \
0                                                NaN
1  The attacker must possess access to the system...
2  The attacker must possess access to the system...
3  None: No specialized resources are required to...
4  None: No specialized resources are required to...

                                  capec_Consequences  \
0                                                NaN
1  Scope: Confidentiality | Impact: Read Data || ...
2  Scope: Confidentiality | Impact: Read Data || ...
3  Scope: Confidentiality, Access Control, Author...
4  Scope: Integrity | Impact: Modify Data || Scop...

                                   capec_Mitigations  \
0                                                NaN
1                                                NaN
2                                                NaN
3  In a J2EE setting, administrators can associat...
4  Configure account privileges such privileged/a...

                             capec_Example_Instances  \
0                                                NaN
1  Using a tool such as 'strings' or similar to p...
2  Using a tool such as 'strings' or similar to p...
3  Implementing the Model-View-Controller (MVC) w...
4  Improperly configured account privileges allow...

                            capec_Related_Weaknesses  \
0                                                NaN
1  CWE-226, CWE-311, CWE-525, CWE-312, CWE-314, C...
2  CWE-226, CWE-311, CWE-525, CWE-312, CWE-314, C...
3  CWE-276, CWE-285, CWE-434, CWE-693, CWE-732, C...
4                         CWE-269, CWE-732, CWE-1317

                             capec_Taxonomy_Mappings  \
0                                                NaN
1  ATTACK: 1005 - Data from Local System || ATTAC...
2  ATTACK: 1005 - Data from Local System || ATTAC...
3  ATTACK: 1574.010 - Hijack Execution Flow: Serv...
4   ATTACK: 1548 - Abuse Elevation Control Mechanism

                     capec_Mitre_Techniques Technique_ID_Only         ID  \
0                                       NaN               NaN        NaN
1             1005 - Data from Local System              1005      T1005
2          1552.004 - Unsecured Credentials          1552.004  T1552.004
3          1574.010 - Hijack Execution Flow          1574.010  T1574.010
4  1548 - Abuse Elevation Control Mechanism              1548      T1548

                                             STIX ID  \
0                                                NaN
1  attack-pattern--3c4a2599-71ee-4405-ba1e-0e2841...
2  attack-pattern--60b508a1-6a5e-46b1-821a-9f7b78...
3  attack-pattern--9e8b28c9-35fe-48ac-a14d-e6cc03...
4  attack-pattern--67720091-eee3-4d2d-ae16-826456...

                                                name  \
0                                                NaN
1                             Data from Local System
2                Unsecured Credentials: Private Keys
3  Hijack Execution Flow: Services File Permissio...
4                  Abuse Elevation Control Mechanism

                                    tech_description  \
0                                                NaN
1  Adversaries may search local system sources, s...
2  Adversaries may search for private key certifi...
3  Adversaries may execute their own malicious pa...
4  Adversaries may circumvent mechanisms designed...

                                             url           created  \
0                                            NaN               NaN
1      https://attack.mitre.org/techniques/T1005       31 May 2017
2  https://attack.mitre.org/techniques/T1552/004  04 February 2020
3  https://attack.mitre.org/techniques/T1574/010     12 March 2020
4      https://attack.mitre.org/techniques/T1548   30 January 2020

     last modified             domain  version  \
0              NaN                NaN      NaN
1    12 April 2023  enterprise-attack      1.6
2  04 October 2024  enterprise-attack      1.2
3    30 March 2023  enterprise-attack      1.0
4  15 October 2024  enterprise-attack      1.4

                                             tactics  \
0                                                NaN
1                                         Collection
2                                  Credential Access
3  Defense Evasion, Persistence, Privilege Escala...
4              Defense Evasion, Privilege Escalation

                                           detection  \
0                                                NaN
1  Monitor processes and command-line arguments f...
2  Monitor access to files and directories relate...
3  Look for changes to binaries and service execu...
4  Monitor the file system for files that have th...

                                           platforms  \
0                                                NaN
1                     Linux, Network, Windows, macOS
2                     Linux, Network, Windows, macOS
3                                            Windows
4  IaaS, Identity Provider, Linux, Office Suite, ...

                                        data sources is sub-technique  \
0                                                NaN              NaN
1  Command: Command Execution, File: File Access,...            False
2      Command: Command Execution, File: File Access             True
3  File: File Creation, File: File Modification, ...             True
4  Command: Command Execution, File: File Metadat...            False

  sub-technique of defenses bypassed  \
0              NaN               NaN
1              NaN               NaN
2            T1552               NaN
3            T1574               NaN
4              NaN               NaN

                                        contributors permissions required  \
0                                                NaN                  NaN
1             Austin Clark, @c2defense; William Cain                  NaN
2  Austin Clark, @c2defense; Itzik Kotler, SafeBr...                  NaN
3             Stefan Kanthak; Travis Smith, Tripwire  Administrator, User
4                                                NaN  Administrator, User

  supports remote                                system requirements  \
0             NaN                                                NaN
1           False  Privileges to access certain files and directo...
2           False                                                NaN
3           False                                                NaN
4           False                                                NaN

  impact type        effective permissions  \
0         NaN                          NaN
1         NaN                          NaN
2         NaN                          NaN
3         NaN  Administrator, SYSTEM, User
4         NaN                          NaN

                              relationship citations
0                                                NaN
1  (Citation: FireEye SUNBURST Backdoor December ...
2  (Citation: MSTIC FoggyWeb September 2021),(Cit...
3  (Citation: F-Secure BlackEnergy 2014),(Citatio...
4  (Citation: TrendMicro RaspberryRobin 2022),(Ci...

In [77]:
# Initialize new columns
device_Attack_Pattern['technique'] = None
device_Attack_Pattern['subtechnique'] = None

def classify_id(row):
    tech_id = row['Technique_ID_Only']
    if pd.isna(tech_id):
        return pd.Series([None, None])
    if '.' in str(tech_id):
        parent_id = str(tech_id).split('.')[0]
        return pd.Series([parent_id, tech_id])
    else:
        return pd.Series([tech_id, None])


# Apply classification
device_Attack_Pattern[['technique', 'subtechnique']] = device_Attack_Pattern.apply(classify_id, axis=1)

In [78]:
# Create a cleaned version of Technique_ID_Only in mitre_df
mitre_df['Technique_ID_Only'] = mitre_df['ID'].str.replace('T', '', regex=False)

# Technique name and tactics lookup
id_to_name = mitre_df.set_index('Technique_ID_Only')['name'].to_dict()
id_to_tactics = mitre_df.set_index('Technique_ID_Only')['tactics'].to_dict()

# For technique column
device_Attack_Pattern['technique_name'] = device_Attack_Pattern['technique'].map(id_to_name)
device_Attack_Pattern['tactics'] = device_Attack_Pattern['technique'].map(id_to_tactics)


device_Attack_Pattern['subtechnique_name'] = device_Attack_Pattern['subtechnique'].map(id_to_name)

In [79]:
# Define the list of columns you want to keep
# Create the final dataframe with selected columns
final_df = device_Attack_Pattern[[
    'CVE ID',
    'Description',
    'attackVector',
    'baseScore',
    'baseSeverity',
    'attackComplexity',
    'privilegesRequired',
    'userInteraction',
    'confidentialityImpact',
    'availabilityImpact',
    'integrityImpact',
    'exploitabilityScore',
    
    #CAPEC details
    'capec_Name',
    'capec_Mitre_Techniques',        # assuming this is what you mean by 'tactics'
    "capec_Abstraction",
    "capec_Status",
    "capec_Description",
    "capec_Extended_Description",
    "capec_Likelihood_Of_Attack",
    "capec_Typical_Severity",
    "capec_Execution_Flow",
    "capec_Prerequisites",
    "capec_Skills_Required",
    'capec_Resources_Required',
    "capec_Consequences",
    "capec_Mitigations",
    "capec_Example_Instances",
    "capec_Related_Weaknesses",
    "capec_Taxonomy_Mappings",

    # Additional CWE details requested
    'cwe_Name',
    'cwe_Abstraction',
    'cwe_Structure',
    'cwe_Status',
    'cwe_Description',
    'cwe_Extended_Description',
    'cwe_Related_Weaknesses',
    'cwe_Weakness_Ordinality',
    'cwe_Language_Name',
    'cwe_Technology_Class',
    'cwe_Alternate_Terms',
    'cwe_Alternate_Terms_With_Descriptions',
    'cwe_Background_Details',
    'cwe_Modes_Of_Introduction',
    'cwe_Likelihood_Of_Exploit',
    'cwe_Common_Consequences',
    'cwe_Detection_Methods',
    'cwe_Potential_Mitigations',
    'cwe_Demonstrative_Examples',
    'cwe_Observed_Examples',

    # Additional MITRE ATT&CK technique/sub-technique fields
    'technique_name',
    'tech_description',
    'subtechnique_name',
    'tactics',
    'detection',
    'platforms',
    'data sources',
    'defenses bypassed',
    'contributors',
    'permissions required',
    'supports remote',
    'system requirements',
    'impact type',
    'effective permissions',

]]
# Step 1: Ensure the 'tactics' column is a list
final_df['tactics'] = final_df['tactics'].str.split(r'\s*,\s*')

# Step 2: Explode the 'tactics' column
final_df = final_df.explode('tactics')

final_df

/tmp/ipykernel_75727/2659015850.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tactics'] = final_df['tactics'].str.split(r'\s*,\s*')

,CVE ID,Description,attackVector,baseScore,baseSeverity,attackComplexity,privilegesRequired,userInteraction,confidentialityImpact,availabilityImpact,integrityImpact,exploitabilityScore,capec_Name,capec_Mitre_Techniques,capec_Abstraction,capec_Status,capec_Description,capec_Extended_Description,capec_Likelihood_Of_Attack,capec_Typical_Severity,capec_Execution_Flow,capec_Prerequisites,capec_Skills_Required,capec_Resources_Required,capec_Consequences,capec_Mitigations,capec_Example_Instances,capec_Related_Weaknesses,capec_Taxonomy_Mappings,cwe_Name,cwe_Abstraction,cwe_Structure,cwe_Status,cwe_Description,cwe_Extended_Description,cwe_Related_Weaknesses,cwe_Weakness_Ordinality,cwe_Language_Name,cwe_Technology_Class,cwe_Alternate_Terms,cwe_Alternate_Terms_With_Descriptions,cwe_Background_Details,cwe_Modes_Of_Introduction,cwe_Likelihood_Of_Exploit,cwe_Common_Consequences,cwe_Detection_Methods,cwe_Potential_Mitigations,cwe_Demonstrative_Examples,cwe_Observed_Examples,technique_name,tech_description,subtechnique_name,tactics,detection,platforms,data sources,defenses bypassed,contributors,permissions required,supports remote,system requirements,impact type,effective permissions
0,CVE-2014-5433,An unauthenticated remote attacker may be able...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CVE-2014-5433,An unauthenticated remote attacker may be able...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Retrieve Embedded Sensitive Data,1005 - Data from Local System,Detailed,Draft,An attacker examines a target system to find s...,NaN,High,Very High,Step 1: Explore - [Identify Target] Attacker i...,In order to feasibly execute this type of atta...,Medium: The attacker must possess knowledge of...,The attacker must possess access to the system...,Scope: Confidentiality | Impact: Read Data || ...,NaN,Using a tool such as 'strings' or similar to p...,"CWE-226, CWE-311, CWE-525, CWE-312, CWE-314, C...",ATTACK: 1005 - Data from Local System || ATTAC...,Cleartext Storage of Sensitive Information,Base,Simple,Draft,The product stores sensitive information in cl...,NaN,"CWE-311 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Mobile, Cloud Computing, ICS/OT",NaN,NaN,NaN,Architecture and Design: OMISSION: This weakne...,NaN,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A,Intro: The following code excerpt stores a pla...,Reference: CVE-2022-30275 | Description: Remot...,Data from Local System,"Adversaries may search local system sources, s...",NaN,Collection,Monitor processes and command-line arguments f...,"Linux, Network, Windows, macOS","Command: Command Execution, File: File Access,...",NaN,"Austin Clark, @c2defense; William Cain",NaN,False,Privileges to access certain files and directo...,NaN,NaN
2,CVE-2014-5433,An unauthenticated remote attacker may be able...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Retrieve Embedded Sensitive Data,1552.004 - Unsecured Credentials,Detailed,Draft,An attacker examines a target system to find s...,NaN,High,Very High,Step 1: Explore - [Identify Target] Attacker i...,In order to feasibly execute this type of atta...,Medium: The attacker must possess knowledge of...,The attacker must possess access to the system...,Scope: Confidentiality | Impact: Read Data || ...,NaN,Using a tool such as 'strings' or similar to p...,"CWE-226, CWE-311, CWE-525, CWE-312, CWE-314, C...",ATTACK: 1005 - Data from Local System || ATTAC...,Cleartext Storage of Sensitive Information,Base,Simple,Draft,The product stores sensitive information in cl...,NaN,"CWE-311 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Mobile, Cloud Computing, ICS/OT",NaN,NaN,NaN,Architecture and Design: OMISSION: This weakne...,NaN,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A,Intro: The following code excerpt stores a pla...,Reference: CVE-2022-30275 | Description: Remot...,Unsecured Credentials,Adversaries may search for private key certifi...,Unsecured Credentials: Private Keys,Credential Access,Monitor access to files and directories relate...,"Linux, Network, Windows, macOS","Command: Command Execution, File: File Access",NaN,"Austin Clark, @c2defense; Itzik Kotler, SafeBr...",NaN,False,NaN,NaN,NaN
3,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",NETWORK,9.4,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,LOW,3.9,Accessing Functionality Not Properly Constrain...,1574.010 - Hijack Execution Flow,Standard,Draft,"In applications, particularly web applications...",NaN,High,High,Step 1: Explore - [Survey] The attacker survey...,The application must be navigable in a manner ...,Low: In order to discover unrestricted resourc...,None: No specialized resources are required to...,"Scope: Confidentiality, Access Control, Author...","In a J2EE setting, administrators can associat...",Implementing the Model-View-Controller (MVC) w...,"CWE-276, CWE-285, CWE-434, CWE-693, CWE-732, C...",ATTACK: 1574.010 - Hijack Execution Flow: Serv...,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,Hijack Execution Flow,Adversaries may execute their own malicious pa...,Hijack Execution Flow: Services File Permissio...,Defense Evasion,Look for changes to binaries and service execu...,Windows,"File: File Creation, File: File Modification, ...",NaN,"Stefan Kanthak; Travis Smith, Tripwire","Administrator, User",False,NaN,NaN,"Administrator, SYSTEM, User"
3,CVE-2020-12041,"The Baxter Spectrum WBM (v17, v20D29, v20D30, ...",NETWORK,9.4,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,LOW,3.9,Accessing Functionality Not Properly Constrain...,1574.010 - Hijack Execution Flow,Standard,Draft,"In applications, particularly web applications...",NaN,High,High,Step 1: Explore - [Survey] The attacker survey...,The application must be navigable in a manner ...,Low: In order to discover unrestricted resourc...,None: No specialized resources are required to...,"Scope: Confidentiality, Access Control, Author...","In a J2EE setting, administrators can associat...",Implementing the Model-View-Controller (MVC) w...,"CWE-276, CWE-285, CWE-434, CWE-693, CWE-732, C...",ATTACK: 1574.010 - Hijack Execution Flow: Serv...,Incorrect Permission Assignment for Critical R...,Class,Simple,Draft,The product specifies permissions for a securi...,When a resource is given a permission setting ...,"CWE-285 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,"Cloud Computing, Not Technology-Specific",NaN,NaN,NaN,Architecture and Design: N/A | Implementation:...,High,Scope: Confidentiality | Impact: Read Applicat...,Method: Automated Static Analysis | Effectiven...,Phase: Implementation | Description: N/A || Ph...,Intro: The following code sets the umask of th...,Reference: CVE-2022-29527 | Description: Go ap...,Hijack Execution Flow,Adversaries may execute their own malicious pa...,Hijack Execution Flow: Services File Permissio...,Persistence,Look for changes to binaries and service execu...,Windows,"File: File Creation, File: File Modification, ...",NaN,"Stefan Kanthak; Travis Smith, Tripwire","Administrator, User",False,NaN,NaN,"Administrator, SYSTEM, User"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Token Impersonation,1134 - Access Token Manipulation,Detailed,Stable,An adversary exploits a weakness in authentica...,NaN,NaN,Medium,NaN,This pattern of attack is only applicable when...,NaN,NaN,Scope: Integrity | Impact: Alter Execution Log...,NaN,NaN,"CWE-287, CWE-1270",ATTACK: 1134 - Access Token Manipulation,Improper Authentication,Class,Simple,Draft,"When an actor claims to have a given identity,...",NaN,"CWE-284 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,ICS/OT,"authentification, AuthN, AuthC","authentification (An alternate term is ""authen...",NaN,Architecture and Design: N/A | Implementation:...,High,"Scope: Integrity, Confidentiality, Availabilit...",Method: Automated Static Analysis | Effectiven...,Phase: Architecture and Design | Description: N/A,Intro: The following code intends to ensure th...,Reference: CVE-2022-35248 | Description: Chat ...,Access Token Manipulation,Adversaries may modify access tokens to operat...,NaN,Privilege Escalation,If an adversary is using a standard command-li...,Windows,Active Directory: Active Directory Object Modi...,"Heuristic Detection, Host Forensic Analysis, S...","Jared Atkinson, @jaredcatkinson; Robby Winches...","Administrator, User",False,NaN,NaN,SYSTEM
49,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Upload a Web Shell to a Web Server,1505.003 - Server Software Component:Web Shell,Detailed,Draft,"By exploiting insufficient permissions, it is ...",NaN,NaN,High,NaN,The web server is susceptible to one of the va...,NaN,NaN,Scope: Confidentiality | Impact: Read Data || ...,Make sure your web server is up-to-date with a...,NaN,"CWE-287, CWE-553",ATTACK: 1505.003 - Server Software Component:W...,Improper Authentication,Class,Simple,Draft,"When an actor claims to have a given identity,...",NaN,"CWE-284 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,ICS/OT,"authentification, AuthN, AuthC","authentification (An alternate term is ""authen...",NaN,Architecture and Design: N/A | Implementation:...,High,"Scope: Integrity, Confidentiality, Availabilit...",Method: Automated Static Analysis | Effectiven...,Phase: Architecture and Design | Description: N/A,Intro: The following code intends to ensure th...,Reference: CVE-2022-35248 | Description: Chat ...,Server Software Component,Adversaries may backdoor web servers with web ...,Server Software Component: Web Shell,Persistence,Web shells can be difficult to detect. Unlike ...,"Linux, Network, Windows, macOS","Application Log: Application Log Content, File...",NaN,"Arnim Rupp, Deutsche Lufthansa AG",NaN,False,NaN,NaN,NaN
50,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Adversary in the Middle (AiTM),1557 - Adversary-in-the-Middle,Meta,Stable,An adversary targets the communication between...,Whenever one component attempts to communicate...,High,Very High,Step 1: Explore - [Determine Communication Mec...,There are two components communicating with ea...,Medium: This attack can get sophisticated sinc...,NaN,Scope: Integrity | Impact: Modify Data || Scop...,Ensure Public Keys are signed by a Certificate...,"In 2017, security researcher Jerry Decime disc...","CWE-300, CWE-290, CWE-593, CWE-287, CWE-294",ATTACK: 1557 - Adversary-in-the-Middle || OWAS...,Improper Authentication,Class,Simple,Draft,"When an actor claims to have a given identity,...",NaN,"CWE-284 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,ICS/OT,"authentification, AuthN, AuthC","authentification (An alternate term is ""authen...",NaN,Architecture and Design: N/A | Implementation:...,High,"Scope: Integrity, Confidentiality, Availabilit...",Method: Automated Static Analysis | Effectiven...,Phase: Architecture and Design | Description: N/A,Intro: The following code intends to ensure th...,Reference: CVE-2022-35248 | Description: Chat ...,Adversary-in-the-Middle,Adversaries may attempt to position themselves...,NaN,Collection,Monitor network traffic for anomalies associat...,"Linux, Network, Windows, macOS","Application Log: Application Log Content, Netw...",NaN,"Daniil Yugoslavskiy, @yugoslavskiy, Atomic Thr...",NaN,False,NaN,NaN,NaN
50,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,Adversary in the Middle (AiTM),1557 - Adversary-in-the-Middle,Meta,Stable,An adversary targets the communication between...,Whenever one component attempts to communicate...,High,Very High,Step 1: Explore - [Determine Communication Mec...,There are two components communicating with ea...,Medium: This attack can get sophisticated sinc...,NaN,Scope: Integrity | Impact: Modify Data || Scop...,Ensure Public Keys are signed by a Certificate...,"In 2017, security researcher Jerry Decime disc...","CWE-300, CWE-290, CWE-593, CWE-287, CWE-294",ATTACK: 1557 - Adversary-in-the-Middle || OWAS...,Improper Authentication,Class,Simple,Draft,"When an actor claims to have a given identity,...",NaN,"CWE-284 (ChildOf, View: 1000, Ordinal: Primary...",NaN,NaN,ICS/OT,"authentification, AuthN, AuthC","authentification (An alternate term is ""authen...",NaN,Architecture and Design: N/A | Implementation:...,High,"Scope: Integrity, Confidentiality, Availabilit...",Method: Automated Static Analysis | Effectiven...,Phase: Architecture and Design | Description: N/A,Intro: The following code intends to ensure th...,Reference: CVE-2022-35248 | Description: Chat ...,Adversary-in-the-Middle,Adversaries may attempt to position themselves...,NaN,Credential Access,Monitor network traffic for anomalies associat...,"Linux, Network, Windows, macOS","Application Log: Application Log Content, Netw...",NaN,"Daniil Yugoslavskiy, @yugoslavskiy, Atomic Thr...",NaN,False,NaN,NaN,NaN
51,CVE-2014-5432,Baxter SIGMA Spectrum Infusion System version ...,NETWORK,9.8,CRITICAL,LOW,NONE,NONE,HIGH,HIGH,HIGH,3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEPRECATED: Authentication Bypass Issues,Class,Simple,Deprecated,This weakness has been deprecated because it c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
device_Attack_Pattern.to_excel('Device_Attack_Pattern.xlsx', index=False)

In [81]:
final_df.to_excel("../3.Visualizations/device_compromise_dataset.xlsx", index=False)